#!/bin/sh
set -e
case "${1:-}" in
    remove|deconfigure|upgrade)
        if [ -d /run/systemd/system ]; then
            systemctl stop abpki-cli.service abpkid.service
            if [ "$1" != upgrade ]; then
                systemctl disable abpki-cli.service abpkid.service
            fi
        fi
        ;;
esac
